application:
  name: live-graphql
  project: live
  publicly_accessible: true
databases:
- type: postgresql
  version: "10"
  name: live
routers:
- name: my-router
  routes:
  - application_name: live-graphql
    paths:
    - /