version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - mysql-compose-network
  app:
    image: node:16
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - APP_SECRET=$APP_SECRET
      - PORT=$PORT
      - API_KEY=$API_KEY
      - NODE_ENV=$NODE_ENV
    stdin_open: true
    tty: true
    networks:
      - mysql-compose-network
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge

volumes: 
  db: